version: '3'

services:
  redis:
    image: redis:5-alpine
    restart: always
    volumes:
      - redis_data:/var/lib/redis
    ports:
      - 6379:6379

networks:
  default:
      name: dev_env
volumes:
  redis_data:
    driver: local
